fix: handle cli_input_json files w/o parent directory (using cli_input_json_directory)

diff --git a/bin/ec2 b/bin/ec2
--- a/bin/ec2
+++ b/bin/ec2
@@ -355,18 +355,25 @@ launch () {
     local launch_template="--launch-template LaunchTemplateId=${__ids[__enum_template]}"
   fi
 
-  if [ -n "$__cli_input_json" ] && [ "$__cli_input_json" != "select" ];then
-    if [[ ! "$__cli_input_json" =~ ^file:// ]];then
-      __cli_input_json="file://$__cli_input_json"
-    fi
-    local cli_input_json="--cli-input-json $__cli_input_json"
-    name="$(basename "${__cli_input_json%.json}")"
-  elif [ "$__cli_input_json"  = "select" ];then
+  if [ "$__cli_input_json"  = "select" ];then
     _select "$(command ls "$__cli_input_json_directory")"
     if [ -n "$__selected" ];then
-      local cli_input_json="--cli-input-json file://$__cli_input_json_directory/$__selected"
-      name="$(basename "${__selected%.json}")"
+      __cli_input_json="$__selected"
     fi
+  fi
+  if [ -n "$__cli_input_json" ];then
+    name="$(basename "${__cli_input_json%.json}")"
+    if [[ ! "$__cli_input_json" =~ ^file:// ]];then
+      if [ -f "$__cli_input_json" ];then
+        __cli_input_json="file://$__cli_input_json"
+      elif [ -f "$__cli_input_json_directory/$__cli_input_json" ];then
+        __cli_input_json="file://$__cli_input_json_directory/$__cli_input_json"
+      else
+        echo "cli_input_json is not found: $__cli_input_json" 1>&2
+        exit 1
+      fi
+    fi
+    local cli_input_json="--cli-input-json $__cli_input_json"
   fi
   __instance_filter="--filters Name=instance-state-name,Values=pending,running,stopping,stopped"
   _get_instance_list
